version: '3.3'
services:
  nginx:
    image: nginx:latest
    container_name: amandla-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./src:/var/www/html:rw,cached
      - ./certs:/etc/certs
    depends_on:
      - wordpress
    networks: 
      - amandla

  mysql:
    image: mariadb
    container_name: amandla-mysql
    volumes:
       - 'amandla-data:/var/lib/mysql:delegated'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=amandla
    ports:
      - '3306:3306'
    networks: 
      - amandla
    

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amandla-wordpress
    volumes:
      - ./src:/var/www/html:rw,cached
      - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      - WORDPRESS_DB_NAME=amandla
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_PASSWORD=password
    depends_on:
      - mysql
    networks: 
      - amandla

  composer:
    image: composer/composer
    container_name: amandla-composer
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html:rw,cached

volumes:
  amandla-data:

networks: 
  amandla:
    driver: bridge