FROM webdevops/php-apache
MAINTAINER Marcin Koziej <marcin@cahoots.pl>

ENV WEB_DOCUMENT_ROOT /app/web
ENV WEB_ALIAS_DOMAIN *.sample.the-open.net

VOLUME /app/web/app/uploads

ADD ./src/ /app/

RUN curl -o /usr/local/bin/wp https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
    chmod +x /usr/local/bin/wp


